services:
  kafka-broker:
    # outside container excess by : localhost:19092
    # inside container excess by : kafka-broker:9092
    image: apache/kafka:4.0.0
    container_name: kafka-broker
    ports:
      - "19092:19092" 
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      # Listeners
      KAFKA_LISTENERS: PLAINTEXT://kafka-broker:9092,PLAINTEXT_EXTERNAL://0.0.0.0:19092,CONTROLLER://kafka-broker:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:9092,PLAINTEXT_EXTERNAL://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

    restart: unless-stopped
  
  kafka-client:
    image: python:3.9
    container_name: kafka-client
    command: ["/bin/sh", "/my_kafka/k_entrypoint.sh"]
    environment:
      - BOOTSTRAP_SERVERS=kafka-broker:9092  # Internal Kafka broker address
    volumes:
      - ./my_kafka:/my_kafka
      - ./requirements.txt:/requirements.txt
      - ./.env:/.env
    depends_on:
      - kafka-broker
